owner: HPCSLab # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Web Page
    url: https://www.hpcs.cs.tsukuba.ac.jp
  - name: Internal Page
    url: https://www.hpcs.cs.tsukuba.ac.jp/internal/pukiwiki/
  - name: Webmail
    url: https://mail.hpcs.cs.tsukuba.ac.jp
  - name: Mail (SMTP)
    url: mail.hpcs.cs.tsukuba.ac.jp
    port: 25
    check: "tcp-ping"

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: HPCS Status Page
  introTitle: HPCS Status Page
  introMessage: HPCSの基幹系の死活監視をします
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: HPCSLab
      href: https://www.hpcs.cs.tsukuba.ac.jp/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
